# Generated by Django 5.1.2 on 2024-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_blog_create_at_blog_update_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(default="", upload_to="blog_images/"),
            preserve_default=False,
        ),
    ]
